# Generated by Django 3.0.2 on 2020-01-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_react_app', '0002_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='info',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
